# -*- coding: utf-8 -*-
# Copyright (C) 2013-Today  Carlos Eduardo Vercelino - CLVsol
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).

{
    'name': 'Person (customizations for CLVhealth-JCAFB Solution)',
    'summary': 'Person Module customizations for CLVhealth-JCAFB Solution.',
    'version': '3.0.0',
    'author': 'Carlos Eduardo Vercelino - CLVsol',
    'category': 'Generic Modules/Others',
    'license': 'AGPL-3',
    'website': 'https://github.com/CLVsol',
    'depends': [
        'clv_person',
        'clv_employee',
        'clv_document',
        'clv_community',
        'clv_event',
        'clv_lab_test',
    ],
    'data': [
        'security/ir.model.access.csv',
        'views/person_view.xml',
        'views/person_code_view.xml',
        'views/person_annotation_view.xml',
        'views/address_view.xml',
        'views/person_reg_state_view.xml',
        'views/person_state_view.xml',
        'views/person_direct_mail_view.xml',
        'views/community_view.xml',
        'views/event_view.xml',
        'views/summary_file_system_view.xml',
        'views/data_export_view.xml',
        'views/data_export_document_item_view.xml',
        'views/data_export_lab_test_criterion_view.xml',
        'views/document_view.xml',
        'views/community_member_view.xml',
        'views/event_attendee_view.xml',
        'views/lab_test_view.xml',
        'views/person_history_view.xml',
        'data/person_seq.xml',
        'data/document.xml',
        'data/community_member.xml',
        'data/event_attendee.xml',
        'data/lab_test.xml',
        'wizard/person_updt_view.xml',
        'wizard/person_direct_mail_setup_view.xml',
        'wizard/person_document_setup_view.xml',
        'views/person_menu_view.xml',
        'views/person_direct_mail_menu_view.xml',
    ],
    'demo': [],
    'test': [],
    'init_xml': [],
    'test': [],
    'update_xml': [],
    'installable': True,
    'application': False,
    'active': False,
    'css': [],
}
